steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/siama-284423/siama_ws:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/siama-284423/siama_ws:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'siamaws', '--region=us-east1', '--platform=managed', '--image=gcr.io/siama-284423/siama_ws:$SHORT_SHA']



    